###
GET http://localhost:3000/api/categories

###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Makanan",
  "image": "https://example.com/food.jpg"
}

###
GET http://localhost:3000/api/categories/1

###
PUT http://localhost:3000/api/categories/1
Content-Type: application/json

{
  "name": "Makanan",
  "image": "https://example.com/food.jpg"
}

###
DELETE http://localhost:3000/api/categories/1

###
PUT http://localhost:3001/api/products/1
Content-Type: application/json

{
  "name": "Es Teh Manis",
  "description": "Minuman segar",
  "status": "active",
  "category_ids": [1, 2]
}



### PUT Order
PUT https://api.dev.accolaplay.id/v2/kafe/dashboard/orders
Content-Type: application/json

{
  "order_number":"ORD-1763023497509-444",
  "status": "PROCESSING"
}
